/**
 * i18n
 */

function messages(key) {
  var code = getLanguage();
  if (!!code && i18n[code]) {
    return i18n[code][key];
  }
  return i18n['en'][key];
}

function getLanguage() {
  return Session.getActiveUserLocale();
}

// translations
var i18n = {
  "en": {
    "title": "Emotional Analyser",
    "subtitle": "Analyse the emotion in your inbox.",
    "subtext": "<p>How sad or happy, positive or negative, are your emails? Analyse email using AI techniques such as sentiment analysis to rate the feelings ggenerated by the email content among others.</p>" + 
        "<p>Summarize the email content.</p>" +
        "<p>Generate suggested hashtags based on the content of the email and even detect the language used.</p>" + 
        "<p>Discover which things are being discussed in the email and the emotions associated with those things.</p>" + 
        "<p>Classify the types of information in the email content, for instance does the email contain News, Games information, etc.</p>",
    "action": "[ Analyse ]",
    "results": "Results",
    "entity": "Entity",
    "pre": "Awaiting analysis",
    "post": "Analysed",
    "status": "Status",
    "tbd": "<Analysis to be done...>",
    "emptydataset" : "Nothing could be discovered within this email content for this particular type of analysis, for instance a summary requires a sufficient amount of data, and entity analysis requires certain concepts to be defined within the email content.",
    "analysisFailed": "Failed to analyse the content of the message",
    "responseTooLarge": "The response size exceeds the capacity of the system.",
    "sentiment.title": "Sentiment Analysis",
    "sentiment.subtitle": "Score the email's emotional sentiment.",
    "sentiment.label": "Sentiment",
    "sentiment.subtext": "Sentiment of a document in terms of polarity (positive or negative) and subjectivity (subjective or objective).",
    "label.sentiment.polarity": "Polarity: ",
    "label.sentiment.subjectivity": "Subjectivity: ",
    "label.sentiment.confidence": "Score: ",
    "summary.title": "Summary",
    "summary.subtitle": "Summarize the email content.",
    "summary.label": "Summary",
    "summary.subtext": "Summarizes an article into a few key sentences.",
    "entity.title": "Entity Extraction",
    "entity.subtitle": "Discover people, places, etc.",
    "entity.label": "Entities",
    "entity.subtext": "Entity Extraction looks at the structural patterns in a document to find and extract entities.",
    "hashtags.title": "Hashtag Suggestions",
    "hashtags.subtitle": "Generate a list of hashtags.",
    "hashtags.label": "Hashtags",
    "hashtags.subtext": "Generate a list of hashtags that will help you associate content with similar information on social media platforms.",
    "languageDetection.title": "Language Detection",
    "languageDetection.subtitle": "Determine the language of the email.",
    "languageDetection.label": "Language Detection",
    "languageDetection.subtext": "Detect the language of any text or URL swiftly and accurately, and returns it as an ISO 639-1 language code.",
    "classification.title": "Classification",
    "classification.subtitle": "Discover types of information.",
    "classification.label": "Classification",
    "classification.subtext": "Determine the type of information contained within the email if it can be classified.",
    "entitySentiment.title": "Entity Level Sentiment",
    "entitySentiment.subtitle": "Sentiment for entities in the email.",
    "entitySentiment.label": "Entity Level Sentiment",
    "entitySentiment.subtext": "The Entity-level Sentiment Analysis (ELSA) endpoint provides the sentiment associated with entity mentioned in a document."
  }
}
